import type { Metadata, Viewport } from 'next';
import './globals.css';
import 'katex/dist/katex.min.css';

export const metadata: Metadata = {
  title: 'CrackJEE: AI-powered JEE preparation',
  description:
    'Practice JEE Main & Advanced questions generated by AI. Track weak areas. Score higher.',
  keywords: ['JEE', 'JEE Main', 'JEE Advanced', 'IIT preparation', 'AI tutor', 'practice questions'],
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
