'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { isAuthenticated } from '@/lib/auth';

const features = [
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
      </svg>
    ),
    title: 'AI-generated questions',
    desc: 'Every question is freshly generated with full JEE syllabus awareness and validated for mathematical correctness before you see it.',
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
      </svg>
    ),
    title: 'Weak area tracking',
    desc: 'The platform detects topics where your success rate drops below 60% and flags them so you focus effort where it counts.',
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" />
      </svg>
    ),
    title: 'Never repeat a question',
    desc: 'Question tracking ensures you never see the same question twice. The pool refreshes intelligently per topic.',
  },
];

const steps = [
  {
    num: '01',
    title: 'Choose subject & topic',
    desc: 'Select from Mathematics, Physics, or Chemistry. Pick any syllabus topic and difficulty level.',
  },
  {
    num: '02',
    title: 'Get a fresh AI question',
    desc: 'A fresh JEE-style question is generated on the fly and validated for correctness before you see it.',
  },
  {
    num: '03',
    title: 'Get instant feedback',
    desc: 'Wrong answer? Get the full explanation. Your weak areas are tracked and surfaced in your dashboard.',
  },
];

export default function LandingPage() {
  const router = useRouter();
  useEffect(() => {
    if (isAuthenticated()) router.replace('/dashboard');
  }, [router]);

  return (
    <>
      {/* ── Header ── */}
      <header className="landing-header">
        <span className="landing-logo">CrackJEE</span>
        <nav className="landing-nav">
          <Link href="/login" className="btn btn-ghost btn-sm">Sign in</Link>
          <Link href="/register" className="btn btn-primary btn-sm">Get started free</Link>
        </nav>
      </header>

      {/* ── Hero ── */}
      <section className="hero-section">
        <div className="hero-badge">
          <span className="badge badge-gray">JEE Main & Advanced · Free during beta</span>
        </div>

        <h1 className="display hero-title">
          Crack JEE with<br />
          AI-powered practice
        </h1>

        <p className="hero-sub">
          Questions generated by AI. Tracks your weak areas automatically.
          Practice smarter, not harder.
        </p>

        <div className="hero-ctas">
          <Link href="/register" className="btn btn-primary btn-lg">Start practicing free</Link>
          <Link href="/login" className="btn btn-outline btn-lg">Sign in</Link>
        </div>

        <div className="hero-proof">
          <span className="hero-proof-item">
            <span className="hero-proof-dot" />
            Physics
          </span>
          <span className="hero-proof-item">
            <span className="hero-proof-dot" />
            Chemistry
          </span>
          <span className="hero-proof-item">
            <span className="hero-proof-dot" />
            Mathematics
          </span>
          <span className="hero-proof-item">
            <span className="hero-proof-dot" />
            No cost, ever
          </span>
        </div>
      </section>

      <div className="divider" />

      {/* ── Features ── */}
      <section className="features-section">
        <p className="section-label text-center">Why CrackJEE</p>
        <h2 className="h1 text-center" style={{ maxWidth: 500, margin: '0 auto' }}>
          Built around how toppers actually study
        </h2>

        <div className="features-grid">
          {features.map((f) => (
            <div key={f.title} className="feature-card">
              <div className="feature-icon" style={{ color: 'var(--gray-700)' }}>{f.icon}</div>
              <p className="feature-title">{f.title}</p>
              <p className="feature-desc">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── How it works ── */}
      <div style={{ background: 'var(--gray-50)', borderTop: '1px solid var(--gray-200)', borderBottom: '1px solid var(--gray-200)' }}>
        <section className="steps-section">
          <p className="section-label">How it works</p>
          <h2 className="h1" style={{ maxWidth: 420 }}>Three steps to better scores</h2>

          <div className="steps-grid">
            {steps.map((s) => (
              <div key={s.num}>
                <p className="step-num">{s.num}</p>
                <p className="step-title">{s.title}</p>
                <p className="step-desc">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>
      </div>

      {/* ── CTA ── */}
      <section className="cta-section">
        <p className="cta-title">Ready to start?</p>
        <p className="cta-sub">
          Join students already preparing for JEE with AI-powered practice.
        </p>
        <Link href="/register" className="btn btn-primary btn-lg">Create free account</Link>
      </section>

      {/* ── Footer ── */}
      <footer className="landing-footer">
        <span className="caption">© 2026 CrackJEE</span>
        <span className="caption">Built for IIT aspirants</span>
      </footer>
    </>
  );
}
